name: Build Dylinject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Xcode command-line tools
        run: |
          sudo xcode-select --install || true

      - name: Downgrade project format for Xcode compatibility
        run: |
          sed -i '' 's/LastUpgradeCheck = [0-9]*;/LastUpgradeCheck = 76;/' dylinject.xcodeproj/project.pbxproj
          sed -i '' 's/objectVersion = [0-9]*;/objectVersion = 55;/' dylinject.xcodeproj/project.pbxproj
          # Replace unsupported file system synchronized group classes
          sed -i '' 's/PBXFileSystemSynchronizedRootGroup/PBXGroup/g' dylinject.xcodeproj/project.pbxproj

      - name: Build Dylinject
        run: |
          xcodebuild \
            -project dylinject.xcodeproj \
            -scheme dylinject \
            -configuration Release \
            -derivedDataPath build
